---
## Play
- hosts: app_hosting
  tasks: 
    - name: Edit /etc/hosts
      linefile:
        dest: /etc/hosts
        line: "127.0.0.1       recettes.wiki 
               127.0.0.1       politique.wiki"
    - name: install php
      apt:
        name: php7.4
        state: present 
    - name: Install apache2
      apt:
        name: apache2
        state: present    
