---
## Play
- hosts: app_hosting
  tasks:
 
## Environment initialization
    - name: Edit /etc/hosts
      linefile:
        dest: /etc/hosts
        line: "127.0.0.1       recettes.wiki 
               127.0.0.1       politique.wiki"
    - name: install php
      apt:
        name: 
          - php7.3
          - apache2
        state: present   

## Download Dokuwiki

    - name: Download dokuwiki
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src

    - name: Unzip dokuwiki
      unarchive:
        remote_src: yes # The archive is already on the remote machine, not on the control machine
        src: /usr/src/dokuwiki-stable.tgz
        dest: /usr/src

    - name: Rename dokuwiki directory
      command: mv /usr/src/dokuwiki-2020-07-29 /usr/src/dokuwiki 

    - name: Delete downloaded archive
      file:
        path: /usr/src/dokuwiki-stable.tgz
        state: absent

## Virtualhost
  ## Recette
    - name: Copy dokuwiki in /recettes_wiki
      command: cp -r /usr/src/dokuwiki /var/www/recettes_wiki

    - name: Change permissions of /recettes_wiki
      file:
        path: /var/www/recettes_wiki
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Copy recettes.wiki config
      copy:
        src: files/recettes-wiki.conf
        dest: /etc/apache2/sites-available/recettes-wiki.conf

  ## Politique
    - name: Copy dokuwiki in /politique_wiki
      command: cp -r /usr/src/dokuwiki /var/www/politique_wiki

    - name: Change permissions of /politique_wiki
      file:
        path: /var/www/politique_wiki
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Copy politique.wiki config
      copy:
        src: files/politique-wiki.conf
        dest: /etc/apache2/sites-available/politique-wiki.conf
