---
## Play
- hosts : all
  tasks:
    - name: Install nmap
      apt: 
        name: nmap
        state: present
    - name: Install vim 
      apt: 
        name: vim
        state: present
## Play
- hosts: role_hosting
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

# Correction du copie coller
    - name: "Créer le dossier /tmp/s2e1/"
      file: 
        state: directory
        path: /tmp/s2e1

    - name: "Créer un fichier /tmp/s2e1/demo avec le texte 'demo' dedans"
      copy: 
        content: "demo"
        dest: /tmp/s2e1/demo

    - name: "créer le dossier /tmp/s2e2/"
      file:
        state: directory
        path: /tmp/s2e2

    - name: "copier ce fichier vers /tmp/s2e2/demo2"
      copy:
        remote_src: yes
        src: /tmp/s2e1/demo
        dest: /tmp/s2e2/demo2
      #copy: 
        #src: /tmp/s2e1/demo
        #dest: /tmp/s2e2/demo2
      #delegate_to: "{{ inventory_hostname }}"  
## Play
- hosts: app_hosting
  tasks: 
    - name: Create directory
      file: 
        path: /tmp/toto
        state: directory

